[WIP] Initial text field
uwblueprint/dancefest-mobile pull request #16
Opened 2018-03-03 01:34 UTC by jtaaa

Still missing for this to merge:
* Unit tests

Also to note:
* Have not seen the way it is rendered on iOS as yet. There may be differences in the rendering.

2018-03-03 01:42 UTC, jtaaa commented
The reason for the extra padding on the `largeTextField` is because the `textAlignVertical: 'top'` causes the text to be closer to the top of the `TextInput` box.

2018-03-06 01:15 UTC, georgeke commented on components/TextField/index.js
> +                 multiline={this.props.large}
Perhaps use a `numLines` prop instead of a `large` boolean? Gives us more flexibility later and avoids hardcoding line numbers.

2018-03-06 01:19 UTC, georgeke requested changes

2018-03-06 01:19 UTC, georgeke commented on components/TextField/index.js
> +  render() {
Add PropTypes

2018-03-06 01:19 UTC, georgeke commented on components/TextField/index.js
> +});
Need a new line

2018-03-06 01:19 UTC, georgeke commented on components/TextField/index.js
> +      {this.props.title && <Text style={styles.titleText}>{this.props.title}</Text>}
Don't need a title since we are going to have a CritiqueSection that will take a title and an input (such as your TextField)

2018-03-06 02:51 UTC, georgeke requested changes

2018-03-06 02:51 UTC, georgeke commented on components/TextField/index.test.js
> +});
new line

2018-03-06 02:51 UTC, georgeke commented on components/TextField/index.js
> +    numberOfLines: PropTypes.number,
let's have this take input.value and input.onChange from redux-form Field as props, and use them

2018-03-06 11:39 UTC, katrinacrisostomo commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/7652499a-75e7-4a53-b4d2-47726289c68a-70ac6b0b-e353-4022-be5a-f4fd7d83dfc2-v1.png?transparent=1&palette=1&width=246)

2018-03-06 18:12 UTC, georgeke approved these changes

2018-03-06 18:55 UTC, merged